# Generated by Django 2.1.5 on 2019-02-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_item', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('descritpion_item', models.TextField(blank=True, null=True)),
                ('media_item', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('link_item', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('alt_item', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('order_item', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('order_item',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_page', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('link_to', models.CharField(blank=True, max_length=30, null=True)),
                ('order_page', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('order_page',),
            },
        ),
        migrations.CreateModel(
            name='PagePara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
            ],
        ),
        migrations.CreateModel(
            name='ParaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_para', models.CharField(db_index=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('title_section', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('order_para', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Type')),
            ],
            options={
                'ordering': ('order_para',),
            },
        ),
        migrations.AddField(
            model_name='paraitem',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paragraph'),
        ),
        migrations.AddField(
            model_name='pagepara',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paragraph'),
        ),
    ]
