# Generated by Django 2.1.5 on 2019-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepara',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagepara',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='type',
        ),
        migrations.RemoveField(
            model_name='paraitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='paraitem',
            name='paragraph',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PagePara',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='ParaItem',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
