# Generated by Django 2.1.5 on 2019-03-06 09:28

import api.assets.DefineDir
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190227_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_item',
            field=models.FileField(blank=True, null=True, upload_to=api.assets.DefineDir.definer_root),
        ),
    ]
