# Generated by Django 2.1.5 on 2019-03-06 09:44

import api.models.Items
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190306_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_item',
            field=models.FileField(blank=True, null=True, upload_to=api.models.Items.definer_root),
        ),
    ]
