# Generated by Django 2.1.5 on 2019-03-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190313_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='title_paras',
            new_name='title_para',
        ),
    ]
