# Generated by Django 2.1.5 on 2019-03-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190313_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('page',),
            },
        ),
        migrations.CreateModel(
            name='ParaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item')),
            ],
            options={
                'ordering': ('paragraph',),
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='paragraph',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='item',
        ),
        migrations.AddField(
            model_name='paraitem',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paragraph'),
        ),
        migrations.AddField(
            model_name='pagepara',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page'),
        ),
        migrations.AddField(
            model_name='pagepara',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Paragraph'),
        ),
    ]
