# Generated by Django 2.1.5 on 2019-03-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190313_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepara',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagepara_page', to='api.Page'),
        ),
        migrations.AlterField(
            model_name='pagepara',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagepara_paragraph', to='api.Paragraph'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_type', to='api.Type'),
        ),
        migrations.AlterField(
            model_name='paraitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraitem_item', to='api.Item'),
        ),
        migrations.AlterField(
            model_name='paraitem',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraitem_aragraph', to='api.Paragraph'),
        ),
    ]
