# Generated by Django 2.1.5 on 2019-03-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190313_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagepara',
            options={'ordering': ('paragraph',)},
        ),
        migrations.AlterModelOptions(
            name='paraitem',
            options={'ordering': ('item',)},
        ),
        migrations.RemoveField(
            model_name='page',
            name='link_to',
        ),
        migrations.AlterField(
            model_name='page',
            name='order_page',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
